### ISSUE TITLE
`is_builtin_module(module_name)`

### ISSUE THREAD

**Issue by smarie** [jackmaney/python-stdlib-list#21]
Thanks for this great package, it was a relief to find it: indeed in my package `getversion` I needed a reliable way to detect if a module is built-in so as to return the system version in that case. I ended up creating a method for this: https://github.com/smarie/python-getversion/blob/master/getversion/plugin_builtins.py

However it would seem much more natural that it is in `stdlib-list`, dont you think?

**Comment by encukou** [comment]
Please standardize the terminology on “builtin” vs. “stdlib”.

For `imp.is_builtin`, “builtin” means “C module compiled into the Python executable” – which is quite strict:

```
>>> import imp
>>> imp.is_builtin('zipimport')  # built in
1
>>> imp.is_builtin('math')       # C-API stdlib module, but linked as extension (on my machine)
0
>>> imp.is_builtin('numpy')      # C-API extension, not stdlib
0
>>> imp.is_builtin('sys')        # built-in (and special)
-1
>>> imp.is_builtin('os')         # Python code in stdlib
0
>>> imp.is_builtin('requests')   # Python code, not stdlib
0
```

**Comment by smarie** [comment]
Thanks for the feedback. 

I opened a PR proposing a new `in_stdlib(module_name, version=None)` method relying on `@lru_cache` for maximum efficiency.

@encukou as of now the `in_stdlib` method has exactly the same semantics than the already available `stdlib_list` method, to preserve consistency. However I totally agree that your exlanation should appear much more clearly, at least in the documentation. I would recommend to open a dedicated issue for this, so that we can then debate on the best way to address it.
