### ISSUE TITLE
update pip install line to use 'stdlib-list' instead

### ISSUE THREAD

**Issue by rapha-opensource** [jackmaney/python-stdlib-list#4]
Clearly not a huge deal, but trying to remove a little confusion.
From the [docs](http://python-stdlib-list.readthedocs.io/en/latest/install.html)
I got "pip install stdlib_list".
But if one searches for it like this:
```shell
pip search stdlib_list
```
It yields nothing. That got me confused.

If instead you search for 'stdlib-list', you can see it:
```shell
pip search stdlib-list
```

**Comment by jackmaney** [comment]
Good catch. Thanks!
