### ISSUE TITLE
Room in this project for Indexing Pypi too?

### ISSUE THREAD

**Issue by chalbersma** [jackmaney/python-stdlib-list#43]
I know in in theory possible to index packages in pypi too. Would this project be open to work to index and store packages. In theory we could parse their api, and grab the `packages` variable out of setup.py

**Comment by ocefpaf** [comment]
This is beyond the scope of this project, not a bad idea, but it does not belong on stdlib  ;-p

BTW, Python 3.10 will probably list all of its modules making this one legacy (py<=3.9). So we are not going to have new version of stdlib after Python 3.10 is released.
