### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [jackmaney/python-stdlib-list#44]
This was reported in https://bugzilla.redhat.com/show_bug.cgi?id=1897245 . It seems `3.10` is missing from long_versions variable as I can see from previous PR that added 3.9 : https://github.com/jackmaney/python-stdlib-list/commit/eec6d91388611caf54ec634c9973a4f56d56132b

**Comment by jackmaney** [comment]
Python 3.10 is still in alpha (the most recent release, as of this writing, being 3.10.0 alpha 5). While 3.10 is still in this state, changes to built-in modules are still possible. Once 3.10.0 final is out ([which has a current ETA of 2021-10-04](https://www.python.org/dev/peps/pep-0619/#id5)), please feel free to make an issue and/or pull request.
