### ISSUE TITLE
Can `stdlib_list(version)` default to the current version?

### ISSUE THREAD

**Issue by thebjorn** [jackmaney/python-stdlib-list#5]
I think it would be convenient if this would work (on a python 2.7 installation):

    from stdlib_list import stdlib_list
    stdlib_list() == stdlib_list("2.7")

ie. that the version parameter defaults to the Python version you're running on, since creating that parameter is tedious and non-obvious:

    stdlib_list('.'.join(str(x) for x in sys.version_info[:2]))

**Comment by jackmaney** [comment]
That certainly sounds reasonable. I'll add that feature tonight after work.
