### ISSUE TITLE
Support for Python 3.10 

### ISSUE THREAD

**Issue by yatmanov** [jackmaney/python-stdlib-list#53]
Can we get release for python 3.10? 

This is a great tool! I am using it to include entire standard library to a single executable file since pyinstaller doesn't have this functionality. So far only this package keeps me from updating to the latest python version. 

Related issue and pull request:
https://github.com/jackmaney/python-stdlib-list/issues/44
https://github.com/jackmaney/python-stdlib-list/pull/49

**Comment by yatmanov** [comment]
Turns out there's no need to update this package. Python 3.10 already comes with list of standard modules: https://docs.python.org/3/library/sys.html#sys.stdlib_module_names
And there's discussion on how to use it to include standard library to PyInstaller builds: https://github.com/pyinstaller/pyinstaller/discussions/6824

**Comment by ocefpaf** [comment]
I actually wanted to look into that for a while. I do recommend you to use that but be sure to add both `sys.stdlib_module_names` and `sys.builtin_module_names` to cover everything.
